import { 
  Utensils, 
  ShoppingCart, 
  Bus, 
  Baby, 
  Car, 
  CreditCard, 
  Coins, 
  Shield, 
  Heart, 
  Smile,
  Flower2,
  Dumbbell,
  Activity,
  Brain,
  GraduationCap,
  Home,
  Gift,
  Briefcase
} from "lucide-react";
import { Benefit } from "@/components/benefits/BenefitCard";

export const benefitsData: Benefit[] = [
  // Alimentação
  {
    id: "vr",
    name: "Vale Refeição",
    shortName: "VR",
    description: "Cartão para refeições em restaurantes, lanchonetes e estabelecimentos conveniados.",
    icon: Utensils,
    category: "alimentacao",
    status: "active",
    enrolledCount: 4127,
    eligibleCount: 4500,
    monthlyCost: 850000,
    provider: "VR Benefícios",
    color: "#06b6d4",
  },
  {
    id: "va",
    name: "Vale Alimentação",
    shortName: "VA",
    description: "Cartão para compras em supermercados, padarias, açougues e estabelecimentos alimentícios.",
    icon: ShoppingCart,
    category: "alimentacao",
    status: "active",
    enrolledCount: 3892,
    eligibleCount: 4500,
    monthlyCost: 380000,
    provider: "Alelo",
    color: "#22c55e",
  },

  // Transporte
  {
    id: "vt",
    name: "Vale Transporte",
    shortName: "VT",
    description: "Benefício legal para deslocamento casa-trabalho em transporte público.",
    icon: Bus,
    category: "transporte",
    status: "active",
    enrolledCount: 3245,
    eligibleCount: 4500,
    monthlyCost: 420000,
    provider: "SPTrans",
    color: "#f59e0b",
  },
  {
    id: "mobilidade",
    name: "Mobilidade Corporativa",
    shortName: "MOB",
    description: "Veículo corporativo, combustível e estacionamento para cargos elegíveis.",
    icon: Car,
    category: "transporte",
    status: "active",
    enrolledCount: 89,
    eligibleCount: 150,
    monthlyCost: 156000,
    provider: "Localiza",
    color: "#8b5cf6",
  },

  // Saúde
  {
    id: "saude",
    name: "Plano de Saúde",
    shortName: "PS",
    description: "Assistência médica completa com cobertura nacional e rede credenciada.",
    icon: Heart,
    category: "saude",
    status: "active",
    enrolledCount: 4320,
    eligibleCount: 4500,
    monthlyCost: 720000,
    provider: "Bradesco Saúde",
    color: "#ef4444",
  },
  {
    id: "odonto",
    name: "Plano Odontológico",
    shortName: "PO",
    description: "Cobertura para tratamentos dentários, ortodontia e procedimentos estéticos.",
    icon: Smile,
    category: "saude",
    status: "active",
    enrolledCount: 3890,
    eligibleCount: 4500,
    monthlyCost: 180000,
    provider: "Amil Dental",
    color: "#3b82f6",
  },
  {
    id: "funeral",
    name: "Plano Funeral",
    shortName: "PF",
    description: "Assistência funeral para colaborador e dependentes legais.",
    icon: Flower2,
    category: "saude",
    status: "active",
    enrolledCount: 4500,
    eligibleCount: 4500,
    monthlyCost: 45000,
    provider: "Grupo Zelo",
    color: "#6b7280",
  },

  // Bem-estar
  {
    id: "wellhub",
    name: "Wellhub",
    shortName: "WH",
    description: "Acesso a academias, estúdios e atividades físicas em todo o Brasil.",
    icon: Dumbbell,
    category: "bemestar",
    status: "active",
    enrolledCount: 2145,
    eligibleCount: 4500,
    monthlyCost: 95000,
    provider: "Wellhub",
    color: "#ec4899",
  },
  {
    id: "totalpass",
    name: "TotalPass",
    shortName: "TP",
    description: "Benefício de bem-estar com acesso a academias e atividades físicas.",
    icon: Activity,
    category: "bemestar",
    status: "inactive",
    enrolledCount: 0,
    eligibleCount: 4500,
    monthlyCost: 0,
    provider: "TotalPass",
    color: "#14b8a6",
  },
  {
    id: "saude-mental",
    name: "Saúde Mental",
    shortName: "SM",
    description: "Psicoterapia online, apoio emocional e programas de bem-estar mental.",
    icon: Brain,
    category: "bemestar",
    status: "active",
    enrolledCount: 1876,
    eligibleCount: 4500,
    monthlyCost: 87000,
    provider: "Zenklub",
    color: "#a855f7",
  },
  {
    id: "home-office",
    name: "Auxílio Home Office",
    shortName: "HO",
    description: "Suporte para estrutura de trabalho remoto: internet, mobiliário e equipamentos.",
    icon: Home,
    category: "bemestar",
    status: "active",
    enrolledCount: 2890,
    eligibleCount: 3200,
    monthlyCost: 145000,
    color: "#0ea5e9",
  },

  // Financeiro
  {
    id: "seguro-vida",
    name: "Seguro de Vida",
    shortName: "SV",
    description: "Cobertura para morte, invalidez e doenças graves com capital segurado.",
    icon: Shield,
    category: "financeiro",
    status: "active",
    enrolledCount: 4500,
    eligibleCount: 4500,
    monthlyCost: 120000,
    provider: "SulAmérica",
    color: "#1e3a8a",
  },
  {
    id: "plr",
    name: "Participação nos Lucros",
    shortName: "PLR",
    description: "Programa de participação nos resultados conforme metas e performance.",
    icon: Coins,
    category: "financeiro",
    status: "active",
    enrolledCount: 4200,
    eligibleCount: 4500,
    monthlyCost: 0,
    color: "#eab308",
  },
  {
    id: "cartao-corp",
    name: "Cartão Corporativo",
    shortName: "CC",
    description: "Cartão de crédito para despesas corporativas e viagens a trabalho.",
    icon: CreditCard,
    category: "financeiro",
    status: "active",
    enrolledCount: 342,
    eligibleCount: 500,
    monthlyCost: 28000,
    provider: "Itaú",
    color: "#f97316",
  },

  // Outros
  {
    id: "creche",
    name: "Auxílio Creche",
    shortName: "AC",
    description: "Reembolso ou convênio para creches e berçários para filhos até 6 anos.",
    icon: Baby,
    category: "outros",
    status: "active",
    enrolledCount: 456,
    eligibleCount: 890,
    monthlyCost: 182000,
    color: "#f472b6",
  },
  {
    id: "educacao",
    name: "Auxílio Educação",
    shortName: "AE",
    description: "Subsídio para cursos, graduação, pós-graduação e certificações profissionais.",
    icon: GraduationCap,
    category: "outros",
    status: "active",
    enrolledCount: 1230,
    eligibleCount: 4500,
    monthlyCost: 246000,
    color: "#6366f1",
  },
  {
    id: "flex",
    name: "Benefícios Flexíveis",
    shortName: "FLEX",
    description: "Carteira de pontos para escolha personalizada de benefícios.",
    icon: Gift,
    category: "outros",
    status: "pending",
    enrolledCount: 0,
    eligibleCount: 4500,
    monthlyCost: 0,
    color: "#06b6d4",
  },
  {
    id: "previdencia",
    name: "Previdência Privada",
    shortName: "PP",
    description: "Plano de previdência complementar com contrapartida da empresa.",
    icon: Briefcase,
    category: "financeiro",
    status: "active",
    enrolledCount: 2890,
    eligibleCount: 4500,
    monthlyCost: 290000,
    provider: "Bradesco Vida",
    color: "#16a34a",
  },
];

export const categoryConfig = {
  alimentacao: { label: "Alimentação", color: "#06b6d4" },
  saude: { label: "Saúde", color: "#ef4444" },
  transporte: { label: "Transporte", color: "#f59e0b" },
  bemestar: { label: "Bem-estar", color: "#ec4899" },
  financeiro: { label: "Financeiro", color: "#22c55e" },
  outros: { label: "Outros", color: "#8b5cf6" },
};
