import { Company, CostCenter, CompanyPolicy } from "@/types/company";

export const companiesData: Company[] = [
  {
    id: "1",
    name: "TechCorp Tecnologia S.A.",
    tradeName: "TechCorp",
    cnpj: "12.345.678/0001-90",
    status: "active",
    segment: "Tecnologia",
    address: "Av. Paulista, 1000, 10º andar",
    city: "São Paulo",
    state: "SP",
    phone: "(11) 3000-1000",
    email: "rh@techcorp.com.br",
    website: "www.techcorp.com.br",
    employeeCount: 1850,
    costCenterCount: 12,
    activeBenefits: 15,
    monthlyBudget: 1200000,
    monthlySpent: 1089000,
    erpIntegration: "TOTVS Protheus",
    createdAt: "2018-03-15",
  },
  {
    id: "2",
    name: "Indústria Metalmax Ltda.",
    tradeName: "Metalmax",
    cnpj: "23.456.789/0001-01",
    status: "active",
    segment: "Indústria",
    address: "Rod. Anhanguera, km 45",
    city: "Campinas",
    state: "SP",
    phone: "(19) 3500-2000",
    email: "rh@metalmax.com.br",
    employeeCount: 2340,
    costCenterCount: 18,
    activeBenefits: 12,
    monthlyBudget: 980000,
    monthlySpent: 923000,
    erpIntegration: "SAP SuccessFactors",
    createdAt: "2019-06-20",
  },
  {
    id: "3",
    name: "Varejo Express Comercial S.A.",
    tradeName: "Varejo Express",
    cnpj: "34.567.890/0001-12",
    status: "active",
    segment: "Varejo",
    address: "Rua do Comércio, 500",
    city: "Rio de Janeiro",
    state: "RJ",
    phone: "(21) 2500-3000",
    email: "beneficios@varejoexpress.com.br",
    website: "www.varejoexpress.com.br",
    employeeCount: 4200,
    costCenterCount: 45,
    activeBenefits: 10,
    monthlyBudget: 1800000,
    monthlySpent: 1654000,
    erpIntegration: "Oracle HCM",
    createdAt: "2017-01-10",
  },
  {
    id: "4",
    name: "Banco Financeira Premium S.A.",
    tradeName: "Financeira Premium",
    cnpj: "45.678.901/0001-23",
    status: "active",
    segment: "Financeiro",
    address: "Av. Brigadeiro Faria Lima, 3500",
    city: "São Paulo",
    state: "SP",
    phone: "(11) 4000-4000",
    email: "rh@financeirapremium.com.br",
    website: "www.financeirapremium.com.br",
    employeeCount: 890,
    costCenterCount: 8,
    activeBenefits: 18,
    monthlyBudget: 890000,
    monthlySpent: 812000,
    erpIntegration: "Senior Sistemas",
    createdAt: "2020-09-01",
  },
  {
    id: "5",
    name: "Construtora Edificar Ltda.",
    tradeName: "Edificar",
    cnpj: "56.789.012/0001-34",
    status: "active",
    segment: "Construção",
    address: "Rua das Obras, 200",
    city: "Belo Horizonte",
    state: "MG",
    phone: "(31) 3200-5000",
    email: "dp@edificar.com.br",
    employeeCount: 1560,
    costCenterCount: 22,
    activeBenefits: 8,
    monthlyBudget: 620000,
    monthlySpent: 598000,
    createdAt: "2021-02-15",
  },
  {
    id: "6",
    name: "Startup Inovação Digital Ltda.",
    tradeName: "InovaDigital",
    cnpj: "67.890.123/0001-45",
    status: "pending",
    segment: "Tecnologia",
    address: "Rua da Inovação, 50",
    city: "Florianópolis",
    state: "SC",
    phone: "(48) 3300-6000",
    email: "people@inovadigital.io",
    website: "www.inovadigital.io",
    employeeCount: 85,
    costCenterCount: 3,
    activeBenefits: 0,
    monthlyBudget: 85000,
    monthlySpent: 0,
    createdAt: "2024-01-05",
  },
];

export const costCentersData: CostCenter[] = [
  // TechCorp
  { id: "cc1", companyId: "1", code: "TI-001", name: "Desenvolvimento", manager: "Carlos Oliveira", employeeCount: 450, budget: 350000, spent: 312000 },
  { id: "cc2", companyId: "1", code: "TI-002", name: "Infraestrutura", manager: "Ana Costa", employeeCount: 120, budget: 95000, spent: 89000 },
  { id: "cc3", companyId: "1", code: "RH-001", name: "Recursos Humanos", manager: "Paula Rodrigues", employeeCount: 45, budget: 38000, spent: 35000 },
  { id: "cc4", companyId: "1", code: "FIN-001", name: "Financeiro", manager: "Roberto Mendes", employeeCount: 80, budget: 68000, spent: 62000 },
  { id: "cc5", companyId: "1", code: "COM-001", name: "Comercial", manager: "Paulo Reis", employeeCount: 200, budget: 165000, spent: 148000 },
  { id: "cc6", companyId: "1", code: "MKT-001", name: "Marketing", manager: "Fernanda Lima", employeeCount: 65, budget: 52000, spent: 47000 },
  // Metalmax
  { id: "cc7", companyId: "2", code: "PROD-001", name: "Produção", manager: "José Silva", employeeCount: 1200, budget: 420000, spent: 398000 },
  { id: "cc8", companyId: "2", code: "PROD-002", name: "Qualidade", manager: "Maria Santos", employeeCount: 150, budget: 95000, spent: 88000 },
  { id: "cc9", companyId: "2", code: "LOG-001", name: "Logística", manager: "Pedro Costa", employeeCount: 320, budget: 145000, spent: 132000 },
  // Varejo Express
  { id: "cc10", companyId: "3", code: "LOJA-SP01", name: "Loja SP Centro", manager: "Lucia Ferreira", employeeCount: 85, budget: 45000, spent: 42000 },
  { id: "cc11", companyId: "3", code: "LOJA-SP02", name: "Loja SP Pinheiros", manager: "Marcos Almeida", employeeCount: 72, budget: 38000, spent: 35000 },
  { id: "cc12", companyId: "3", code: "LOJA-RJ01", name: "Loja RJ Centro", manager: "Carla Lima", employeeCount: 95, budget: 52000, spent: 48000 },
];

export const companyPoliciesData: CompanyPolicy[] = [
  // TechCorp policies
  { id: "p1", companyId: "1", benefitId: "vr", benefitName: "Vale Refeição", enabled: true, eligibilityRules: ["CLT", "Tempo mínimo: 0 dias"], monthlyLimit: 880, employeeContribution: 0 },
  { id: "p2", companyId: "1", benefitId: "va", benefitName: "Vale Alimentação", enabled: true, eligibilityRules: ["CLT", "Tempo mínimo: 0 dias"], monthlyLimit: 650 },
  { id: "p3", companyId: "1", benefitId: "vt", benefitName: "Vale Transporte", enabled: true, eligibilityRules: ["Presencial ou Híbrido"], employeeContribution: 6 },
  { id: "p4", companyId: "1", benefitId: "saude", benefitName: "Plano de Saúde", enabled: true, eligibilityRules: ["CLT", "Tempo mínimo: 90 dias"], employeeContribution: 20 },
  { id: "p5", companyId: "1", benefitId: "odonto", benefitName: "Plano Odontológico", enabled: true, eligibilityRules: ["CLT"] },
  { id: "p6", companyId: "1", benefitId: "wellhub", benefitName: "Wellhub", enabled: true, eligibilityRules: ["Adesão voluntária"], employeeContribution: 50 },
  { id: "p7", companyId: "1", benefitId: "home-office", benefitName: "Auxílio Home Office", enabled: true, eligibilityRules: ["Regime remoto ou híbrido"], monthlyLimit: 150 },
  { id: "p8", companyId: "1", benefitId: "educacao", benefitName: "Auxílio Educação", enabled: true, eligibilityRules: ["CLT", "Tempo mínimo: 12 meses", "Aprovação gestão"], monthlyLimit: 500 },
  // Metalmax policies
  { id: "p9", companyId: "2", benefitId: "vr", benefitName: "Vale Refeição", enabled: true, eligibilityRules: ["CLT"], monthlyLimit: 660 },
  { id: "p10", companyId: "2", benefitId: "va", benefitName: "Vale Alimentação", enabled: true, eligibilityRules: ["CLT"], monthlyLimit: 450 },
  { id: "p11", companyId: "2", benefitId: "vt", benefitName: "Vale Transporte", enabled: true, eligibilityRules: ["Todos"], employeeContribution: 6 },
  { id: "p12", companyId: "2", benefitId: "saude", benefitName: "Plano de Saúde", enabled: true, eligibilityRules: ["CLT", "Tempo mínimo: 60 dias"], employeeContribution: 15 },
];

export const statusConfig = {
  active: { label: "Ativa", color: "#22c55e", bgClass: "bg-success/10 text-success border-success/20" },
  inactive: { label: "Inativa", color: "#6b7280", bgClass: "bg-muted text-muted-foreground border-muted" },
  pending: { label: "Pendente", color: "#f59e0b", bgClass: "bg-warning/10 text-warning border-warning/20" },
};

export const segmentConfig: Record<string, { color: string }> = {
  "Tecnologia": { color: "#3b82f6" },
  "Indústria": { color: "#f59e0b" },
  "Varejo": { color: "#22c55e" },
  "Financeiro": { color: "#8b5cf6" },
  "Construção": { color: "#ef4444" },
  "Saúde": { color: "#ec4899" },
  "Educação": { color: "#06b6d4" },
};
