import { Employee, Dependent, BenefitHistory, EligibilityRule } from "@/types/employee";

export const employeesData: Employee[] = [
  {
    id: "1",
    name: "Maria Silva Santos",
    email: "maria.silva@empresa.com",
    position: "Gerente de Projetos",
    department: "Tecnologia",
    costCenter: "TI-001",
    hireDate: "2020-03-15",
    birthDate: "1988-07-22",
    cpf: "123.456.789-00",
    status: "active",
    contractType: "clt",
    workload: 40,
    salary: 15000,
    manager: "Carlos Oliveira",
    location: "São Paulo - SP",
    phone: "(11) 99999-1234",
    activeBenefits: 8,
    totalBenefitsCost: 2850,
    dependentsCount: 2,
  },
  {
    id: "2",
    name: "João Pedro Lima",
    email: "joao.lima@empresa.com",
    position: "Desenvolvedor Senior",
    department: "Tecnologia",
    costCenter: "TI-002",
    hireDate: "2021-08-01",
    birthDate: "1992-11-15",
    cpf: "234.567.890-11",
    status: "active",
    contractType: "clt",
    workload: 40,
    salary: 12000,
    manager: "Maria Silva Santos",
    location: "São Paulo - SP",
    phone: "(11) 98888-5678",
    activeBenefits: 6,
    totalBenefitsCost: 1950,
    dependentsCount: 0,
  },
  {
    id: "3",
    name: "Ana Carolina Ferreira",
    email: "ana.ferreira@empresa.com",
    position: "Analista de RH",
    department: "Recursos Humanos",
    costCenter: "RH-001",
    hireDate: "2019-01-10",
    birthDate: "1990-04-30",
    cpf: "345.678.901-22",
    status: "active",
    contractType: "clt",
    workload: 40,
    salary: 8500,
    manager: "Paula Rodrigues",
    location: "São Paulo - SP",
    phone: "(11) 97777-9012",
    activeBenefits: 7,
    totalBenefitsCost: 2100,
    dependentsCount: 1,
  },
  {
    id: "4",
    name: "Carlos Eduardo Oliveira",
    email: "carlos.oliveira@empresa.com",
    position: "Diretor de Tecnologia",
    department: "Tecnologia",
    costCenter: "TI-000",
    hireDate: "2018-06-01",
    birthDate: "1982-09-12",
    cpf: "456.789.012-33",
    status: "active",
    contractType: "clt",
    workload: 40,
    salary: 28000,
    location: "São Paulo - SP",
    phone: "(11) 96666-3456",
    activeBenefits: 10,
    totalBenefitsCost: 4200,
    dependentsCount: 3,
  },
  {
    id: "5",
    name: "Beatriz Almeida Costa",
    email: "beatriz.costa@empresa.com",
    position: "Analista Financeiro",
    department: "Financeiro",
    costCenter: "FIN-001",
    hireDate: "2022-02-14",
    birthDate: "1995-12-05",
    cpf: "567.890.123-44",
    status: "active",
    contractType: "clt",
    workload: 40,
    salary: 7500,
    manager: "Roberto Mendes",
    location: "São Paulo - SP",
    phone: "(11) 95555-7890",
    activeBenefits: 5,
    totalBenefitsCost: 1650,
    dependentsCount: 0,
  },
  {
    id: "6",
    name: "Ricardo Souza Neto",
    email: "ricardo.souza@empresa.com",
    position: "Estagiário de Marketing",
    department: "Marketing",
    costCenter: "MKT-001",
    hireDate: "2024-01-08",
    birthDate: "2002-03-18",
    cpf: "678.901.234-55",
    status: "active",
    contractType: "intern",
    workload: 30,
    salary: 2000,
    manager: "Fernanda Lima",
    location: "São Paulo - SP",
    phone: "(11) 94444-1234",
    activeBenefits: 3,
    totalBenefitsCost: 450,
    dependentsCount: 0,
  },
  {
    id: "7",
    name: "Fernanda Lima Moreira",
    email: "fernanda.lima@empresa.com",
    position: "Gerente de Marketing",
    department: "Marketing",
    costCenter: "MKT-000",
    hireDate: "2017-11-20",
    birthDate: "1985-06-28",
    cpf: "789.012.345-66",
    status: "onleave",
    contractType: "clt",
    workload: 40,
    salary: 16000,
    location: "São Paulo - SP",
    phone: "(11) 93333-5678",
    activeBenefits: 8,
    totalBenefitsCost: 2900,
    dependentsCount: 2,
  },
  {
    id: "8",
    name: "Lucas Mendonça Silva",
    email: "lucas.silva@empresa.com",
    position: "Consultor Externo",
    department: "Comercial",
    costCenter: "COM-002",
    hireDate: "2023-06-01",
    birthDate: "1991-01-10",
    cpf: "890.123.456-77",
    status: "active",
    contractType: "pj",
    workload: 40,
    salary: 18000,
    manager: "Paulo Reis",
    location: "Rio de Janeiro - RJ",
    phone: "(21) 99999-9999",
    activeBenefits: 2,
    totalBenefitsCost: 0,
    dependentsCount: 0,
  },
];

export const dependentsData: Dependent[] = [
  { id: "d1", employeeId: "1", name: "Pedro Silva Santos", relationship: "child", birthDate: "2015-05-10", cpf: "111.222.333-44", benefits: ["Plano de Saúde", "Plano Odontológico"] },
  { id: "d2", employeeId: "1", name: "Lucas Silva Santos", relationship: "child", birthDate: "2018-09-22", cpf: "222.333.444-55", benefits: ["Plano de Saúde", "Plano Odontológico", "Auxílio Creche"] },
  { id: "d3", employeeId: "3", name: "Marcos Ferreira", relationship: "spouse", birthDate: "1989-02-14", cpf: "333.444.555-66", benefits: ["Plano de Saúde"] },
  { id: "d4", employeeId: "4", name: "Juliana Oliveira", relationship: "spouse", birthDate: "1984-11-30", cpf: "444.555.666-77", benefits: ["Plano de Saúde", "Plano Odontológico"] },
  { id: "d5", employeeId: "4", name: "Gabriel Oliveira", relationship: "child", birthDate: "2010-07-15", cpf: "555.666.777-88", benefits: ["Plano de Saúde", "Plano Odontológico"] },
  { id: "d6", employeeId: "4", name: "Isabella Oliveira", relationship: "child", birthDate: "2014-03-25", cpf: "666.777.888-99", benefits: ["Plano de Saúde", "Plano Odontológico"] },
  { id: "d7", employeeId: "7", name: "Roberto Moreira", relationship: "spouse", birthDate: "1983-08-20", cpf: "777.888.999-00", benefits: ["Plano de Saúde"] },
  { id: "d8", employeeId: "7", name: "Sophia Moreira", relationship: "child", birthDate: "2019-12-01", cpf: "888.999.000-11", benefits: ["Plano de Saúde", "Plano Odontológico", "Auxílio Creche"] },
];

export const benefitHistoryData: BenefitHistory[] = [
  { id: "h1", employeeId: "1", benefitName: "Vale Refeição", action: "enrolled", date: "2020-03-15", details: "Adesão inicial", user: "Sistema" },
  { id: "h2", employeeId: "1", benefitName: "Plano de Saúde", action: "enrolled", date: "2020-03-15", details: "Inclusão titular + 2 dependentes", user: "Sistema" },
  { id: "h3", employeeId: "1", benefitName: "Wellhub", action: "enrolled", date: "2023-01-10", details: "Adesão voluntária", user: "Maria Silva" },
  { id: "h4", employeeId: "1", benefitName: "Vale Transporte", action: "cancelled", date: "2022-06-01", details: "Solicitação do colaborador - trabalho remoto", user: "RH Admin" },
  { id: "h5", employeeId: "2", benefitName: "Vale Refeição", action: "updated", date: "2023-07-01", details: "Upgrade de categoria", user: "RH Admin" },
  { id: "h6", employeeId: "4", benefitName: "Veículo Corporativo", action: "enrolled", date: "2019-01-15", details: "Elegível por cargo - Diretor", user: "Sistema" },
];

export const eligibilityRulesData: EligibilityRule[] = [
  { id: "e1", benefitId: "vr", benefitName: "Vale Refeição", eligible: true, enrolledDate: "2020-03-15" },
  { id: "e2", benefitId: "va", benefitName: "Vale Alimentação", eligible: true, enrolledDate: "2020-03-15" },
  { id: "e3", benefitId: "vt", benefitName: "Vale Transporte", eligible: true, reason: "Trabalho presencial ou híbrido" },
  { id: "e4", benefitId: "saude", benefitName: "Plano de Saúde", eligible: true, enrolledDate: "2020-03-15" },
  { id: "e5", benefitId: "odonto", benefitName: "Plano Odontológico", eligible: true, enrolledDate: "2020-03-15" },
  { id: "e6", benefitId: "wellhub", benefitName: "Wellhub", eligible: true, enrolledDate: "2023-01-10" },
  { id: "e7", benefitId: "seguro-vida", benefitName: "Seguro de Vida", eligible: true, enrolledDate: "2020-03-15" },
  { id: "e8", benefitId: "plr", benefitName: "PLR", eligible: true, reason: "Tempo mínimo: 12 meses", enrolledDate: "2021-03-15" },
  { id: "e9", benefitId: "mobilidade", benefitName: "Veículo Corporativo", eligible: false, reason: "Elegível apenas para Diretores" },
  { id: "e10", benefitId: "creche", benefitName: "Auxílio Creche", eligible: true, reason: "Filhos até 6 anos", enrolledDate: "2020-03-15" },
];

export const statusConfig = {
  active: { label: "Ativo", color: "#22c55e", bgClass: "bg-success/10 text-success border-success/20" },
  inactive: { label: "Inativo", color: "#6b7280", bgClass: "bg-muted text-muted-foreground border-muted" },
  onleave: { label: "Afastado", color: "#f59e0b", bgClass: "bg-warning/10 text-warning border-warning/20" },
  terminated: { label: "Desligado", color: "#ef4444", bgClass: "bg-destructive/10 text-destructive border-destructive/20" },
};

export const contractConfig = {
  clt: { label: "CLT", color: "#3b82f6" },
  pj: { label: "PJ", color: "#8b5cf6" },
  intern: { label: "Estágio", color: "#f59e0b" },
  temporary: { label: "Temporário", color: "#6b7280" },
};

export const relationshipConfig = {
  spouse: "Cônjuge",
  child: "Filho(a)",
  parent: "Pai/Mãe",
  other: "Outro",
};
