import { 
  Database, 
  Server, 
  Cloud, 
  CreditCard, 
  Utensils, 
  ShoppingCart,
  Building2,
  Zap,
  Globe,
  Wallet,
  Receipt,
  FileSpreadsheet
} from "lucide-react";
import { Integration, SyncLog } from "@/types/integration";

export const integrationsData: Integration[] = [
  // ERPs
  {
    id: "protheus",
    name: "TOTVS Protheus",
    shortName: "Protheus",
    description: "ERP corporativo para gestão de RH, folha de pagamento e benefícios.",
    icon: Database,
    type: "erp",
    status: "online",
    lastSync: "2024-01-21T02:45:00Z",
    nextSync: "2024-01-21T03:45:00Z",
    syncFrequency: "Horária",
    recordsProcessed: 15847,
    errorCount: 0,
    uptime: 99.9,
    version: "12.1.33",
    apiEndpoint: "https://api.totvs.com.br/protheus",
    features: ["Colaboradores", "Folha", "Eventos", "Férias", "Rescisão"],
    color: "#1e40af",
  },
  {
    id: "sap-hcm",
    name: "SAP SuccessFactors",
    shortName: "SAP HCM",
    description: "Plataforma de gestão de capital humano e experiência do colaborador.",
    icon: Server,
    type: "erp",
    status: "online",
    lastSync: "2024-01-21T02:30:00Z",
    nextSync: "2024-01-21T03:30:00Z",
    syncFrequency: "Horária",
    recordsProcessed: 8432,
    errorCount: 2,
    uptime: 99.7,
    version: "2H 2023",
    apiEndpoint: "https://api.successfactors.com",
    features: ["Employee Central", "Payroll", "Benefits", "Time Management"],
    color: "#0070f3",
  },
  {
    id: "oracle-hcm",
    name: "Oracle HCM Cloud",
    shortName: "Oracle",
    description: "Suite completa de gestão de recursos humanos na nuvem.",
    icon: Cloud,
    type: "erp",
    status: "degraded",
    lastSync: "2024-01-21T01:15:00Z",
    nextSync: "2024-01-21T03:15:00Z",
    syncFrequency: "A cada 2 horas",
    recordsProcessed: 5621,
    errorCount: 15,
    uptime: 98.2,
    version: "23D",
    apiEndpoint: "https://api.oracle.com/hcm",
    features: ["Core HR", "Payroll", "Benefits", "Workforce Management"],
    color: "#c74634",
  },
  {
    id: "senior",
    name: "Senior Sistemas",
    shortName: "Senior",
    description: "Solução de gestão empresarial com foco em RH e folha.",
    icon: Building2,
    type: "erp",
    status: "online",
    lastSync: "2024-01-21T02:50:00Z",
    nextSync: "2024-01-21T03:50:00Z",
    syncFrequency: "Horária",
    recordsProcessed: 3245,
    errorCount: 0,
    uptime: 99.8,
    version: "G7",
    features: ["Gestão Pessoas", "Folha", "Ponto", "Benefícios"],
    color: "#059669",
  },
  
  // Fornecedores de Benefícios
  {
    id: "vr",
    name: "VR Benefícios",
    shortName: "VR",
    description: "Cartões de vale refeição, alimentação e benefícios flexíveis.",
    icon: Utensils,
    type: "provider",
    status: "online",
    lastSync: "2024-01-21T02:55:00Z",
    nextSync: "2024-01-21T03:55:00Z",
    syncFrequency: "Horária",
    recordsProcessed: 4127,
    errorCount: 0,
    uptime: 99.95,
    version: "API v3",
    apiEndpoint: "https://api.vr.com.br/v3",
    features: ["Recarga", "Saldo", "Extrato", "Bloqueio", "2ª Via"],
    color: "#dc2626",
  },
  {
    id: "alelo",
    name: "Alelo",
    shortName: "Alelo",
    description: "Soluções em alimentação, mobilidade e benefícios corporativos.",
    icon: ShoppingCart,
    type: "provider",
    status: "online",
    lastSync: "2024-01-21T02:40:00Z",
    nextSync: "2024-01-21T03:40:00Z",
    syncFrequency: "Horária",
    recordsProcessed: 3892,
    errorCount: 1,
    uptime: 99.8,
    version: "API v2.1",
    apiEndpoint: "https://api.alelo.com.br",
    features: ["Recarga", "Consulta", "Bloqueio", "Relatórios"],
    color: "#16a34a",
  },
  {
    id: "sodexo",
    name: "Sodexo",
    shortName: "Sodexo",
    description: "Benefícios e incentivos para colaboradores.",
    icon: CreditCard,
    type: "provider",
    status: "online",
    lastSync: "2024-01-21T02:35:00Z",
    nextSync: "2024-01-21T03:35:00Z",
    syncFrequency: "Horária",
    recordsProcessed: 2156,
    errorCount: 0,
    uptime: 99.7,
    version: "API v4",
    features: ["Multi Benefícios", "Recarga", "Saldo", "2ª Via"],
    color: "#ea580c",
  },
  {
    id: "flash",
    name: "Flash Benefícios",
    shortName: "Flash",
    description: "Plataforma flexível de benefícios corporativos.",
    icon: Zap,
    type: "provider",
    status: "online",
    lastSync: "2024-01-21T02:58:00Z",
    nextSync: "2024-01-21T03:58:00Z",
    syncFrequency: "30 minutos",
    recordsProcessed: 1847,
    errorCount: 0,
    uptime: 99.99,
    version: "API v2",
    apiEndpoint: "https://api.flashapp.com.br",
    features: ["Flex", "Recarga", "Saldo", "Categorias", "Limites"],
    color: "#7c3aed",
  },
  {
    id: "caju",
    name: "Caju",
    shortName: "Caju",
    description: "Benefícios flexíveis em um único cartão.",
    icon: Wallet,
    type: "provider",
    status: "syncing",
    lastSync: "2024-01-21T02:00:00Z",
    nextSync: null,
    syncFrequency: "30 minutos",
    recordsProcessed: 1234,
    errorCount: 0,
    uptime: 99.9,
    version: "API v1.5",
    apiEndpoint: "https://api.caju.com.br",
    features: ["Multibenefício", "Recarga", "Cashback"],
    color: "#f59e0b",
  },
  {
    id: "swile",
    name: "Swile",
    shortName: "Swile",
    description: "Cartão de benefícios e experiência do colaborador.",
    icon: Globe,
    type: "provider",
    status: "pending",
    lastSync: null,
    nextSync: null,
    syncFrequency: "Não configurado",
    recordsProcessed: 0,
    errorCount: 0,
    uptime: 0,
    version: "API v1",
    features: ["Multi Benefícios", "Engajamento", "Reconhecimento"],
    color: "#ec4899",
  },
  {
    id: "ticket",
    name: "Ticket",
    shortName: "Ticket",
    description: "Soluções em benefícios de alimentação e refeição.",
    icon: Receipt,
    type: "provider",
    status: "offline",
    lastSync: "2024-01-20T18:30:00Z",
    nextSync: null,
    syncFrequency: "Horária",
    recordsProcessed: 0,
    errorCount: 47,
    uptime: 94.5,
    version: "API v2",
    features: ["Recarga", "Saldo", "Extrato"],
    color: "#0284c7",
  },
  
  // Folha de Pagamento
  {
    id: "adp",
    name: "ADP",
    shortName: "ADP",
    description: "Gestão de folha de pagamento e recursos humanos.",
    icon: FileSpreadsheet,
    type: "payroll",
    status: "online",
    lastSync: "2024-01-21T02:20:00Z",
    nextSync: "2024-01-21T03:20:00Z",
    syncFrequency: "Horária",
    recordsProcessed: 4832,
    errorCount: 0,
    uptime: 99.9,
    version: "GlobalView",
    features: ["Folha", "Eventos", "Descontos", "Exportação"],
    color: "#be123c",
  },
];

export const syncLogsData: SyncLog[] = [
  {
    id: "1",
    integrationId: "protheus",
    timestamp: "2024-01-21T02:45:00Z",
    status: "success",
    message: "Sincronização concluída com sucesso",
    recordsProcessed: 1247,
    duration: 45,
  },
  {
    id: "2",
    integrationId: "vr",
    timestamp: "2024-01-21T02:55:00Z",
    status: "success",
    message: "Recarga processada para 127 colaboradores",
    recordsProcessed: 127,
    duration: 12,
  },
  {
    id: "3",
    integrationId: "oracle-hcm",
    timestamp: "2024-01-21T01:15:00Z",
    status: "warning",
    message: "Sincronização parcial - 15 registros com erro de validação",
    recordsProcessed: 5606,
    duration: 120,
  },
  {
    id: "4",
    integrationId: "ticket",
    timestamp: "2024-01-20T18:30:00Z",
    status: "error",
    message: "Falha na conexão - API indisponível",
    recordsProcessed: 0,
    duration: 0,
  },
  {
    id: "5",
    integrationId: "sap-hcm",
    timestamp: "2024-01-21T02:30:00Z",
    status: "success",
    message: "8.432 registros sincronizados",
    recordsProcessed: 8432,
    duration: 89,
  },
  {
    id: "6",
    integrationId: "flash",
    timestamp: "2024-01-21T02:58:00Z",
    status: "success",
    message: "Saldos atualizados com sucesso",
    recordsProcessed: 1847,
    duration: 8,
  },
];

export const typeConfig = {
  erp: { label: "ERP", color: "#1e40af" },
  provider: { label: "Fornecedor", color: "#16a34a" },
  payroll: { label: "Folha", color: "#7c3aed" },
  other: { label: "Outros", color: "#6b7280" },
};

export const statusConfig = {
  online: { label: "Online", color: "#22c55e", bgClass: "bg-success/10 text-success border-success/20" },
  offline: { label: "Offline", color: "#ef4444", bgClass: "bg-destructive/10 text-destructive border-destructive/20" },
  degraded: { label: "Degradado", color: "#f59e0b", bgClass: "bg-warning/10 text-warning border-warning/20" },
  syncing: { label: "Sincronizando", color: "#3b82f6", bgClass: "bg-info/10 text-info border-info/20" },
  pending: { label: "Pendente", color: "#6b7280", bgClass: "bg-muted text-muted-foreground border-muted" },
};
