project_id = "tnheplroicxpxjnpmrqr"

[functions.hr-chatbot]
verify_jwt = false

[functions.execute-connector-job]
verify_jwt = false

[functions.health-check-connector]
verify_jwt = false

[functions.dlq-reprocess]
verify_jwt = false

[functions.process-import]
verify_jwt = false

[functions.policy-engine]
verify_jwt = false
